on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      ref:
        description: "The existing reference to publish"
        type: "string"
        required: true
jobs:
  publish-flake:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: flakestry/flakestry-publish@main
        with:
          ref: "${{ inputs.ref || github.ref }}"
          url: https://staging.flakestry.dev
